name: CD Pipeline

on:
  release:
    types: [published]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker Image to the registry
      shell: bash
      env:
        # default Github Actions token
        # https://help.github.com/en/github/automating-your-workflow-with-github-actions/authenticating-with-the-github_token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE: docker.pkg.github.com/romitagl/golang_ci_template/go-app-container
      run: |
        VERSION=$(git rev-parse HEAD)
        RELEASE_TAG="${{ github.ref }}"
        echo building Release Docker Image $VERSION $RELEASE_TAG
        make build_docker
        echo tagging tag go-app-container:$VERSION as $DOCKER_IMAGE:$RELEASE_TAG
        docker tag go-app-container:$VERSION $DOCKER_IMAGE:$RELEASE_TAG
        # echo Push the image to GitHub Packages
        docker login docker.pkg.github.com -u publisher -p "${{ secrets.GITHUB_TOKEN }}"
        docker push $DOCKER_IMAGE:$RELEASE_TAG
        # docker push $DOCKER_IMAGE:latest
